# Generated by Django 4.1.1 on 2022-10-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('phone_number', models.IntegerField(max_length=11, unique=True)),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
    ]
